/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "simple_experiment.h"
#include "breadboard_experiment.h"

#define wait_millisecond 1000
uint32_t wait_counter = 0;

int main(void)
{
    // Choose your experiment by uncommenting one of the lines below:        
    
    // Onboard LED experiments (simple_experiment.c):
   // led_sequence();          // LEDs turn on one by one
    // led_blink_original();    // Original: All LEDs blink together
    // led_alternate();         // Red+Yellow vs Blue alternating
    
    // Breadboard simple LED experiments (breadboard_experiment.c):
    // simple_blink();          // Simple on/off blinking (now 3 sec on/off)
   // led_always_on();         // LED always on (for testing PA0 connection)
    // super_slow_blink();      // Very slow blink (10 sec on/off)
    //

	fast_blink();            // Fast blinking
    // sos_pattern();           // SOS morse code pattern
    
    return 0;
}
 
