/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "project.h"
#include "practice.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* =========================
       PRACTICE FILE SELECTOR
       Uncomment ONE of the following lines to run that practice
       ========================= */
    
    // Main project (reflex game)
    // return project_main();
    
    // Practice exercises - uncomment ONE at a time
    return practice1_main();  // GPIO Control - 7-Segment Display
    // return practice2_main();  // Timer Control  
    // return practice3_main();  // ADC Reading
}
